version: '3.5'
services:
    app:
        build: ./docker
        volumes:
            - ./application:/app
        ports:
            - "8001:8000"
        links:
            - postgresql
            - crontab
        networks:
             - network
    postgresql:
        image: postgres:9.6.21-alpine
        ports:
            - "5432:5432"
        networks:
            - network
        volumes:
            - ./database:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: jdasfjnkk3HJSD
            POSTGRES_DB: postgresql
        restart: always
networks:
    network:
        name: network
        external: true
        driver: bridge

